/* AUTOGENERATED FILE. DO NOT EDIT. */
/**
 * @brief 运行测试的宏定义。TestFunc是测试用例函数，TestLineNum是测试用例在源码的行号
 * 
 */
#define RUN_TEST(TestFunc, TestLineNum)            \
	{                                              \
		Unity.CurrentTestName = #TestFunc;         \
		Unity.CurrentTestLineNumber = TestLineNum; \
		Unity.NumberOfTests++;                     \
		if (TEST_PROTECT())                        \
		{                                          \
			setUp();                               \
			TestFunc();                            \
		}                                          \
		if (TEST_PROTECT())                        \
		{                                          \
			tearDown();                            \
		}                                          \
		UnityConcludeTest();                       \
	}

#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "app_code.h"
#include "TestCode.h"
#include "unity_config.h"

int main(void)
{
	/*注意！在unity中不能使用双斜杠的单行注释作为注释语句*/
	UnityBegin("test/TestCode.c");

	RUN_TEST(unit_test_1, 20);

	return (UnityEnd());
}
